#!/usr/bin/env python3
"""
make_sample_logs.py - generate a small, entirely fictional set of Plex-shaped logs.

Nothing here comes from a real server. The line formats match what Plex Media
Server writes, so the sample exercises every rule in plexreport.py's FINDINGS
table and can be regenerated by anyone:

    python3 examples/make_sample_logs.py examples/sample-logs
    python3 plexreport.py examples/sample-logs -o examples/sample-report.html

It also works as a rough test: every finding should appear in the output.
"""

import os
import random
import sys
from datetime import datetime, timedelta

random.seed(20260911)                      # deterministic output

START = datetime(2026, 3, 14, 8, 0, 0)
TITLES = ["Harbour Lights - S02 E04 - The Long Way Round",
          "Quarry Road - S01 E11 - Signal Fire",
          "The Glasshouse Sessions - S04 E02 - Tin and Wire",
          "Northbound - S07 E19 - Six Weeks of Rain"]
CHANNELS = ["XX10001.example-tuner.invalid", "XX10002.example-tuner.invalid",
            "XX10003.example-tuner.invalid"]
CLIENTS = [("10.0.0.31", "Roku", 'Living Room Player'),
           ("10.0.0.52", "Android", 'Kitchen Tablet'),
           ("203.0.113.24", "Plex Web", 'Chrome')]
DECODER = ["ac-tex damaged at {} {}", "mb incr damaged", "slice mismatch",
           "Warning MVs not available", "invalid cbp -1 at {} {}",
           "Invalid mb type in P-frame at {} {}", "skip with previntra"]
ENDPOINTS = ["/library/sections", "/library/metadata/{id}", "/status/sessions",
             "/hubs/continueWatching", "/:/timeline", "/photo/:/transcode",
             "/video/:/transcode/universal/session/{sid}/base/{seg}.ts"]


class Clock:
    def __init__(self, start):
        self.t = start

    def tick(self, lo=0.2, hi=9.0):
        self.t += timedelta(seconds=random.uniform(lo, hi))
        return self.t


def fmt(t):
    return t.strftime("%b %d, %Y %H:%M:%S.") + "%03d" % (t.microsecond // 1000)


class Log:
    def __init__(self, path):
        self.fh = open(path, "w", encoding="utf-8")
        self.thread = random.randint(10 ** 13, 9 * 10 ** 13)

    def w(self, t, level, msg):
        self.fh.write("%s [%d] %s - %s\n" % (fmt(t), self.thread, level, msg))

    def close(self):
        self.fh.close()


def server_log(path, clock, banner=True):
    lg = Log(path)
    if banner:
        lg.w(clock.t, "INFO", "Plex Media Server v1.43.9.0000-abcdef012 - "
                              "Docker Docker Container x86_64 - build: linux-x86_64 debian "
                              "- GMT -05:00")
        lg.w(clock.tick(0, .1), "INFO", "Linux version: 6.6.0-example, language: en-US")
    return lg


def startup(lg, clock):
    lg.w(clock.tick(.1, .4), "INFO", "SQLITE3:0x80000001, 283, recovered 412 frames from "
                                     "WAL file /config/Library/Application Support/Plex Media "
                                     "Server/Plug-in Support/Databases/"
                                     "com.plexapp.plugins.library.db-wal")
    lg.w(clock.tick(.1, .5), "INFO", "Opening 18 database sessions to library "
                                     "(com.plexapp.plugins.library), helper: 0, "
                                     "wal: 1, synchronous: 1")
    lg.w(clock.tick(.1, .5), "INFO", "HttpServer: Listening on port 32400 (IPv4)")
    lg.w(clock.tick(.1, .5), "INFO", "BPQ: [Idle] -> [Starting]")
    lg.w(clock.tick(.1, .5), "INFO", "Running server with 12 CPU cores available")


def traffic(lg, clock, n):
    """Ordinary request/response chatter, the bulk of any real log."""
    for _ in range(n):
        ip, product, device = random.choice(CLIENTS)
        ep = random.choice(ENDPOINTS)
        ep = ep.replace("{id}", str(random.randint(1000, 9999)))
        ep = ep.replace("{sid}", "00000000-0000-4000-8000-%012d" % random.randint(0, 10 ** 11))
        ep = ep.replace("{seg}", "%05d" % random.randint(0, 900))
        port = random.randint(30000, 60000)
        req = random.randint(0x1000, 0xffff)
        t = clock.tick(.05, 1.4)
        lg.w(t, "DEBUG", "Request: [%s:%d (WAN)] GET %s (6 live) #%x TLS "
                         "Signed-in Token (sampleuser)" % (ip, port, ep, req))
        status = random.choices([200, 200, 200, 200, 204, 401, 404], [70, 10, 5, 5, 5, 3, 2])[0]
        ms = random.choices([2, 4, 9, 40, 900], [50, 25, 15, 8, 2])[0]
        lg.w(clock.tick(.01, .2), "DEBUG",
             "Completed: [%s:%d] %d GET %s (6 live) #%x TLS GZIP %dms %d bytes"
             % (ip, port, status, ep, req, ms, random.randint(300, 2_500_000)))


def timeline(lg, clock, rating_key, client_ip, minutes, buffering=0):
    """The play-state updates a client posts while watching."""
    end = clock.t + timedelta(minutes=minutes)
    played = 0
    while clock.t < end:
        state = "playing"
        if buffering and random.random() < 0.03:
            state = "buffering"
            buffering -= 1
        elif random.random() < 0.02:
            state = "paused"
        port = random.randint(30000, 60000)
        ep = ("/:/timeline?ratingKey=%s&state=%s&playbackTime=%d&time=%d&duration=1800000"
              % (rating_key, state, played, played))
        req = random.randint(0x1000, 0xffff)
        lg.w(clock.t, "DEBUG", "Request: [%s:%d (WAN)] GET %s (6 live) #%x TLS "
                               "Signed-in Token (sampleuser)" % (client_ip, port, ep, req))
        lg.w(clock.tick(.01, .05), "DEBUG",
             "Completed: [%s:%d] 200 GET %s (6 live) #%x TLS 3ms 812 bytes"
             % (client_ip, port, ep, req))
        played += 10000
        clock.tick(9.5, 10.5)


def decoder_noise(lg, clock, session, count):
    for _ in range(count):
        msg = random.choice(DECODER).format(random.randint(0, 60), random.randint(0, 40))
        lg.w(clock.tick(.01, .3), "ERROR",
             "[Req#%x/Transcode/%s] [mpeg2video @ 0x7f%09x] %s"
             % (random.randint(0x1000, 0xffff), session, random.randint(0, 10 ** 9), msg))


def session_report(path, start, segments, stall_at=None):
    """A Transcoder Statistics file: one XML SessionReport."""
    rows = []
    clock_ms = 120
    for i in range(segments):
        dur = 1001
        width = 1000 if stall_at is None or i not in stall_at else 46000
        rows.append('      <Segment index="%d" duration="%d">\n'
                    '        <Timelines>\n'
                    '          <Transcode startTime="%d" endTime="%d"/>\n'
                    '          <Download startTime="%d" endTime="%d" complete="1"/>\n'
                    '        </Timelines>\n'
                    '      </Segment>'
                    % (i, dur, clock_ms, clock_ms + width,
                       clock_ms + width, clock_ms + width + 40))
        clock_ms += width
    xml = ('<SessionReport startTimestamp="%s" key="/livetv/sessions/00000000-0000-4000-8000-'
           '000000000001" session="sample-session" transcode="0000aaaa1111bbbb">\n'
           '  <User id="1" title="sampleuser"/>\n'
           '  <Player product="Plex for Roku" platform="Roku" title="Living Room Player"\n'
           '          address="10.0.0.31" local="0" relayed="0" secure="1"/>\n'
           '  <Variants>\n'
           '    <Variant videoDecision="transcode" audioDecision="copy"\n'
           '             sourceVideoCodec="mpeg2video" videoCodec="hevc"\n'
           '             sourceAudioCodec="ac3" audioCodec="ac3"\n'
           '             protocol="hls" container="mpegts" targetBitrate="8000"\n'
           '             transcodeHwRequested="1" transcodeHwEncodingTitle="Nvidia (NVENC)"\n'
           '             transcodeHwDecodingTitle="" transcodeHwFullPipeline="0">\n'
           '      <Media videoResolution="1080" bitrate="12000" origin="livetv"\n'
           '             channelCallSign="EXAMPLE-TV"/>\n'
           '    </Variant>\n'
           '  </Variants>\n'
           '  <SegmentList>\n%s\n  </SegmentList>\n'
           '</SessionReport>\n' % (fmt(start), "\n".join(rows)))
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(xml)


def main(outdir):
    os.makedirs(os.path.join(outdir, "PMS Plugin Logs"), exist_ok=True)
    clock = Clock(START)

    # ---- rotated older log: steady use, decoder noise, a stalled recording ----
    lg = server_log(os.path.join(outdir, "Plex Media Server.1.log"), clock)
    traffic(lg, clock, 400)
    lg.w(clock.tick(), "DEBUG", "[Now] User is sampleuser (ID: 1)")
    lg.w(clock.tick(), "DEBUG", "[Now] Device is Roku (Living Room Player)")
    lg.w(clock.tick(), "DEBUG", "MDE: %s: no direct play video profile exists for "
                                "hls/mpegts/mpeg2video/ac3" % TITLES[0])
    session = "00000000-0000-4000-8000-000000000001"
    decoder_noise(lg, clock, session, 900)
    timeline(lg, clock, "4101", "10.0.0.31", 40, buffering=3)
    lg.w(clock.tick(), "ERROR", "[Req#41a1/LiveTV] Recording failed. Please check your tuner "
                                "or antenna.")
    lg.w(clock.tick(), "ERROR", "HttpClient: Couldn't connect to server "
                                "http://10.0.0.90:80/discover.json")
    traffic(lg, clock, 250)
    lg.w(clock.tick(), "INFO", "Added new metadata item (Quarry Road) with ID 4102")
    lg.w(clock.tick(), "WARN", "[Req#4210] Webhook: Error delivering payload to "
                               "https://hooks.example.invalid/plex (000)")
    lg.close()

    # ---- current log: crash, restart, database trouble ----------------------
    clock.tick(60, 90)
    lg = server_log(os.path.join(outdir, "Plex Media Server.log"), clock)
    startup(lg, clock)
    traffic(lg, clock, 200)
    for _ in range(9):
        lg.w(clock.tick(2, 30), "ERROR",
             "[Req#%x] SQLITE3:0x%x, 11, database disk image is malformed"
             % (random.randint(0x1000, 0xffff), random.randint(0, 0xffffffff)))
    lg.w(clock.tick(), "ERROR", "SQLITE3:0x0, 11, database corruption at line 82310 of "
                                "[1b37c146ee]")
    lg.w(clock.tick(), "ERROR", "Butler: The database failed its integrity check, not backing up")
    lg.w(clock.tick(), "ERROR", "Butler: wasn't able to back up your database")
    lg.w(clock.tick(), "ERROR", "[Req#4d01/Database optimization] Fixup threw an exception: "
                                "database disk image is malformed")
    lg.w(clock.tick(), "ERROR", "Butler: Uncaught exception running subtask "
                                "BuildGracenoteCollections")
    lg.w(clock.tick(), "ERROR", "IsDirWritable: directory '/transcode' is not writable")
    lg.w(clock.tick(), "ERROR", "IsFileWritable: failed to create file "
                                "'/transcode/00000000-0000-4000-8000-000000000009'")
    lg.w(clock.tick(), "DEBUG", "Jobs: '/usr/lib/plexmediaserver/Plex Transcoder' exit code "
                                "for process 4417 is -9 (signal: Killed)")
    lg.w(clock.tick(), "ERROR", "[Req#4e02/Transcode] Conversion failed. The transcoder "
                                "process crashed.")
    lg.w(clock.tick(), "WARN", "Terminated session 12 with reason Conversion failed")
    lg.w(clock.tick(), "ERROR", "Got exception from request handler: sqlite3_statement_backend"
                                "::prepare: database disk image is malformed")
    lg.w(clock.tick(), "WARN", "[MetadataAgent] Match request for 'Unknown Title' returned "
                               "no metadata")
    lg.w(clock.tick(), "ERROR", "[Req#4f10] buildIndexFile: part has no video stream, "
                                "extraction has failed after multiple previous retry attempts")
    lg.w(clock.tick(), "DEBUG", "Butler: Starting task BackupDatabase")
    lg.w(clock.tick(), "DEBUG", "Butler: Starting task RefreshLibraries")
    decoder_noise(lg, clock, session, 420)
    timeline(lg, clock, "4102", "10.0.0.52", 25, buffering=2)
    traffic(lg, clock, 300)
    lg.w(clock.tick(), "INFO", "Added new metadata item (Northbound) with ID 4103")
    lg.close()

    # ---- side-car logs ------------------------------------------------------
    lg = Log(os.path.join(outdir, "Plex Crash Uploader.log"))
    lg.w(clock.t, "INFO", "Session Health - Status: crashed, Version: 1.43.9.0000-abcdef012, "
                          "Duration: 6h 12m")
    lg.close()

    lg = Log(os.path.join(outdir, "Plex Media Scanner.log"))
    lg.w(clock.tick(), "INFO", "Plex Media Scanner v1.43.9.0000-abcdef012 - Docker Container")
    lg.w(clock.tick(), "DEBUG", "Running: /usr/lib/plexmediaserver/Plex Media Scanner "
                                "--scan --refresh --section 3")
    lg.w(clock.tick(), "INFO", "Opening 2 database sessions to library "
                               "(com.plexapp.plugins.library), helper: 1, wal: 1")
    lg.w(clock.tick(), "WARN", "[UltraBlurProcessor] Failed to extract colours for item 4103")
    lg.close()

    with open(os.path.join(outdir, "PMS Plugin Logs", "com.plexapp.system.log"),
              "w", encoding="utf-8") as fh:
        for lvl, msg in (("INFO", "Starting framework core - Python 2.7.18"),
                         ("CRITICAL", "Exception in thread named 'Startup' "
                                      "(most recent call last):"),
                         ("CRITICAL", "  File \"Framework/core.py\", line 812, in _run"),
                         ("CRITICAL", "Exception: Private handlers are no longer supported"),
                         ("INFO", "Plug-in initialised")):
            fh.write("%s (7f0000aa0000) : %s (core:349) - %s\n"
                     % (clock.tick().strftime("%Y-%m-%d %H:%M:%S,%f")[:-3], lvl, msg))

    session_report(os.path.join(outdir, "Plex Transcoder Statistics.log"),
                   START + timedelta(minutes=12), 1800)
    session_report(os.path.join(outdir, "Plex Transcoder Statistics.1.log"),
                   START + timedelta(hours=3), 900, stall_at={210, 640, 641})

    print("wrote sample logs to %s" % outdir)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "sample-logs")
